# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 976475e266320e713b5589d962be077a34ffea8b31c32c61a2c09d39d8b8a6275cd44cd527db3f6fef5c6aed1a5087d3b83cd8ff39906109beb04fbb146f242f

test:
  secret_key_base: d2cef86ffeab577439e8dfe7f01399cbcf3cb0b51ab1ff84a4beef2ac05434c9fe0e59689f5704cf243d1e968fa3fc8ecb568328e5eb460f87e141debba84da4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
